//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public System.DateTime Dtm_Crt { get; set; }
        public string L1 { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime Last_Update { get; set; }
        public Nullable<System.DateTime> OnProgressDate { get; set; }
        public Nullable<System.DateTime> OnWaitingDate { get; set; }
        public Nullable<System.DateTime> OnHoldDate { get; set; }
        public Nullable<System.DateTime> ResolvedTime { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public string Technician { get; set; }
        public string Status { get; set; }
        public int UsersId { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual DueDate DueDate1 { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual User User { get; set; }
    }
}
